name: CI
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 7
      - uses: actions/setup-node@v3.8.1
        with:
          node-version: 18.x
          cache: "pnpm"

      - run: pnpm install --no-frozen-lockfile
      - run: pnpm run build:cli
