name: Publish
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
  push:
    branches:
      - "main"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 7
      - uses: actions/setup-node@v3.8.1
        with:
          node-version: 18.x
          cache: "pnpm"

      - name: Install NPM Dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build the package
        run: pnpm build:cli

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1.4.5
        with:
          version: .github/update-lock.sh
          publish: npx changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
